language: cpp

apt:
    sources:
    - boost-latest
    packages:
    - libboost1.58-all-dev

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository -y ppa:sickpig/boostx
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev=1.58
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -Dtest=on ..

script:
  - ls /usr/include/boost/multiprecision
  - make && make test
