language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository -y ppa:sickpig/boost
  - sudo apt-get update -qq
  - sudo apt-get install boost1.58
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -Dtest=on ..

script: make && make test
