language: cpp

apt:
    sources:
    - boost-latest
    packages:
    - libboost1.58-all-dev

compiler:
  - gcc
  - clang

before_script:
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -Dtest=on ..

script: make && make test
