language: cpp

apt:
    sources:
    - boost-latest
    packages:
    - libboost1.58-all-dev

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-all-dev
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -Dtest=on ..

script:
  - ls /usr/include 
  - make && make test
