language: cpp

addons:
  apt:
    sources:
    - sickpig
    packages:
    - libboost-all-dev

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository -y ppa:sickpig/boost
  - sudo apt-get update -qq
  - sudo apt-cache policy libboost-all-dev
  - sudo apt-get install libboost-all-dev
  - mkdir build
  - cd build
  - cmake -G "Unix Makefiles" -Dtest=on ..

script:
  - ls /usr/include/boost/multiprecision
  - make && make test
